# Generated by Django 2.0.7 on 2018-08-01 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=16, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('token', models.CharField(max_length=256)),
                ('photo', models.FileField(blank=True, upload_to='')),
                ('newbe', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=256)),
                ('cat_img', models.ImageField(blank=True, upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_3166_a2', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CountryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_3166_a2', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('iso_4217', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange_Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_from', to='api.Currencies')),
                ('exchange_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_to', to='api.Currencies')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery_Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='')),
                ('in_active', models.BooleanField(default=True)),
                ('price', models.FloatField(default=0)),
                ('delprice', models.FloatField(default=0)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Currencies')),
                ('iso_3166_a2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Itemsinset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ItemStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('iso_3166_a2', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img', models.ImageField(blank=True, upload_to='img')),
                ('logo_name', models.CharField(max_length=64)),
                ('uzver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_status_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Languages')),
            ],
        ),
        migrations.CreateModel(
            name='Order_statuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(default=0.0)),
                ('status', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('delivery_adress', models.CharField(max_length=420)),
                ('delivery_datetime', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=1)),
                ('kids_count', models.IntegerField(default=0)),
                ('buyer_fullname', models.CharField(max_length=200)),
                ('buyer_phone', models.CharField(max_length=200)),
                ('checkid', models.CharField(max_length=200)),
                ('is_paid', models.BooleanField(default=False)),
                ('birthday', models.CharField(blank=True, max_length=36)),
                ('city', models.CharField(blank=True, max_length=36)),
                ('sex', models.CharField(blank=True, max_length=36)),
                ('description', models.TextField(blank=True)),
                ('description_img', models.ImageField(blank=True, upload_to='img')),
                ('currencies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Currencies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdersItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('city', models.IntegerField(default=0)),
                ('kids_price', models.FloatField(default=0)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('main_img', models.ImageField(blank=True, upload_to='img')),
                ('is_set', models.BooleanField(default=False)),
                ('in_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('share', models.TextField(default='gg wp')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Categories')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Logo')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ItemStatus')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('descriptions', models.TextField(blank=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Languages')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Products')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_name', models.CharField(max_length=256)),
                ('reg_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='RegionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Languages')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Set_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('descriptions', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Languages')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ItemSet')),
            ],
        ),
        migrations.AddField(
            model_name='ordersitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Products'),
        ),
        migrations.AddField(
            model_name='ordersitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Orders'),
        ),
        migrations.AddField(
            model_name='order_status_detail',
            name='order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Order_statuses'),
        ),
        migrations.AddField(
            model_name='itemsinset',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_in_set', to='api.Products'),
        ),
        migrations.AddField(
            model_name='itemsinset',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set', to='api.Products'),
        ),
        migrations.AddField(
            model_name='itemset',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Region'),
        ),
        migrations.AddField(
            model_name='itemset',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gallery_photo',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Products'),
        ),
        migrations.AddField(
            model_name='countrydetails',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Languages'),
        ),
        migrations.AddField(
            model_name='categorydetails',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Languages'),
        ),
    ]
