# Generated by Django 2.1 on 2018-10-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_products_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='reservdate',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
