from django.conf.urls import url
from app import views

urlpatterns = [

    url(r'^.*\.html', views.gentella_html, name='gentella'),
    url(r'^$', views.mainpage, name='index'),
    url(r'login', views.confirmcode, name='confirmcode'),
    url(r'itemlist', views.itemlist, name='itemlist'),
    url(r'addlogohandler', views.addlogohandler, name='addlogohandler'),
    url(r'createitemhandle', views.createitemhandle, name='createitemhandle'),
    url(r'createitem', views.createitem, name='createitem'),
    url(r'edit/(?P<id>\d+)', views.edititemhandle, name='edititemhandle'),
    url(r'acceptorder/(?P<id>\d+)', views.confirmorder, name='confirmorder'),
    url(r'editset/(?P<id>\d+)', views.editset, name='editset'),
    url(r'edititem/(?P<id>\d+)', views.edititem, name='edititem'),
    url(r'reservedate/(?P<id>\d+)', views.reservedate, name='reservedate'),
    url(r'deactivate/(?P<id>\d+)', views.deactivate, name='deactivate'),
    url(r'moderate/(?P<id>\d+)', views.moderate, name='moderate'),
    url(r'unsetpop/(?P<id>\d+)', views.unsetpop, name='unsetpop'),
    url(r'setpop/(?P<id>\d+)', views.setpop, name='setpop'),
    url(r'unban/(?P<id>\d+)', views.unban, name='unban'),
    url(r'ban/(?P<id>\d+)', views.ban, name='ban'),
    url(r'orderlist_all', views.orderlist_all, name='orderlist_all'),
    url(r'orderlist_new', views.orderlist_new, name='orderlist_new'),
    url(r'orderlist_finished', views.orderlist_finished, name='orderlist_finished'),
    url(r'editprofilehandle', views.editprofilehandle, name='editprofilehandle'),
    url(r'editprofile', views.editprofile, name='editprofile'),
    url(r'profile', views.profile, name='profile'),
    url(r'endsession', views.endsession, name='endsession'),
    url(r'userlist', views.userlist, name='userlist'),
    url(r'admin-items', views.itemlistforadmall, name='itemlistforadmall'),
    url(r'admin-new-items', views.itemlistforadmnew, name='itemlistforadmnew'),
    url(r'admin-pop-items', views.itemlistforadmpop, name='itemlistforadmpop'),
    url(r'admin-sets', views.setlistforadmall, name='itemlistforadmall'),
    #url(r'admin-new-sets', views.setlistforadmnew, name='itemlistforadmnew'),
    url(r'admin-pop-sets', views.setlistforadmpop, name='itemlistforadmpop'),
    url(r'admin-stats', views.astat, name='astat'),
    url(r'freshorders', views.freshorders, name='freshorders'),
    url(r'admin-orderlist-finished', views.admin_orderlist_finished, name='admin_orderlist_finished'),
    url(r'admin-orderlist-new', views.admin_orderlist_new, name='admin_orderlist_new'),
    url(r'handlercreateset', views.createsethandler, name='createsethandler'),
    url(r'createset', views.createset, name='createset'),
    url(r'logo', views.logo, name='logo'),
    url(r'editsethandler', views.editsethandler, name='editsethandler'),

]